name: Ejecución de acciones de TestBoost

on:
  push:
    branches:
      - main
      - develop
      - release
  pull_request:
    types:
      - closed
    branches:
      - main
      - develop
      - release
         

jobs:
  test_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio TestBoost
      uses: actions/checkout@v3
      with:
        repository: javalenciacai/test.james.suma
        ref: ${{ github.ref }}

    - name: Ejecutar script de instalación de dependencias
      run: |
        sudo timedatectl set-timezone America/Bogota
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Ejecutar script de sumar
      continue-on-error: true
      run: pytest src/test_suites/ui --html=src/report/report.html --self-contained-html
