name: Ejecución de acciones de TestBoost

on:
  push:
  pull_request:
    types:
      - closed
    branches:
      - main
      - develop
      - release
         

jobs:
  test_ui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio TestBoost
      uses: actions/checkout@v3
      with:
        repository: javalenciacai/test.james.suma
        ref: ${{ github.ref }}

    - name: Ejecutar script de instalación de dependencias
      run: |
        sudo timedatectl set-timezone America/Bogota
        source venv/bin/activate
        pip install -r requirements.txt
        playwright install 

    - name: Ejecutar script de sumar
      if: ${{ always() }}
      run: pytest src/test_suites/ui --html=src/report/report.html --self-contained-html --base-url=https://jamesfrontsuma${{ github.ref }}.jamesvalencia1.repl.co/


    # Publish HTML report
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: HTML-report
        path: src/report/
